before_script:
    - composer self-update
    - composer install --dev
script:
    - phpunit --coverage-text --coverage-clover=coverage.clover
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
language: php
php:
  - '7.0'
notifications:
    email: false
